# Generated by Django 5.1.3 on 2024-12-03 16:19

from django.db import migrations


# up-migration
def add_roles(apps, schema_editor):
    Role = apps.get_model("users", "Role")
    roles = ["staff", "supervisor", "admin"]
    for role_name in roles:
        Role.objects.get_or_create(name=role_name)


# no down-migration required in this case


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_remove_role_description"),
    ]

    operations = [
        migrations.RunPython(add_roles),
    ]
