# Generated by Django 5.1.3 on 2024-12-04 13:06

from django.db import migrations
from django.contrib.auth import get_user_model


def create_superuser(apps, schema_editor):
    User = get_user_model()
    if not User.objects.filter(username="admin").exists():
        User.objects.create_superuser(
            username="admin",
            email="admin@example.com",
            password="adminpassword",
        )


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_managers_remove_user_created_at_and_more"),
    ]

    operations = [
        migrations.RunPython(create_superuser),
    ]
